/*
 Navicat Premium Data Transfer

 Source Server         : Maria DB Local
 Source Server Type    : MariaDB
 Source Server Version : 50560
 Source Host           : localhost:3306
 Source Schema         : db_pdamtkrsip

 Target Server Type    : MariaDB
 Target Server Version : 50560
 File Encoding         : 65001

 Date: 01/04/2019 12:25:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for p_setting_item
-- ----------------------------
DROP TABLE IF EXISTS `p_setting_item`;
CREATE TABLE `p_setting_item`  (
  `id_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_setting` int(11) NOT NULL,
  `nama_item` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `id_parent` int(11) NOT NULL,
  `urutan` int(11) NOT NULL,
  `meta_value` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id_item`) USING BTREE,
  INDEX `id_setting`(`id_setting`, `nama_item`, `id_parent`, `urutan`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 975 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of p_setting_item
-- ----------------------------
INSERT INTO `p_setting_item` VALUES (1, 1, 'Home', 0, 1, '{\"path_kanal\":\"\",\"path_root\":\"\",\"status\":\"on\",\"keterangan\":\"Halaman Utama\",\"tipe\":\"biasa\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (38, 1, 'Tutorial Website', 0, 2, '{\"path_kanal\":\"tutorial_website\",\"path_root\":\"tutorial_website\",\"status\":\"on\",\"keterangan\":\"kajak\",\"tipe\":\"liputan\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (3, 1, 'Dokumentasi Portalid', 0, 3, '{\"path_kanal\":\"dokumentasi_portalid\",\"path_root\":\"dokumentasi_portalid\",\"status\":\"on\",\"keterangan\":\"-\",\"tipe\":\"liputan\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (40, 1, 'Tutorial HTML', 38, 1, '{\"path_kanal\":\"tutorial_html\",\"path_root\":\"tutorial_website\",\"status\":\"on\",\"keterangan\":\"asd\",\"tipe\":\"biasa\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (41, 1, 'Tutorial PHP & MySQL', 38, 2, '{\"path_kanal\":\"tutorial_php___mysql\",\"path_root\":\"tutorial_website\",\"status\":\"on\",\"keterangan\":\"-\",\"tipe\":\"biasa\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (294, 1, 'Baru Sekarang', 0, 4, '{\"path_kanal\":\"baru_sekarang\",\"path_root\":\"baru_sekarang\",\"status\":\"on\",\"keterangan\":\"mnmn\",\"tipe\":\"liputan\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (307, 2, 'Sistem', 73, 3, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (62, 3, '', 0, 0, '{\"id_menu\":\"95\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (93, 5, 'Identitas Aplikasi', 0, 1, '{\"nama_aplikasi\":\"SIMPEG\",\"slogan_aplikasi\":\"PDAM TKR Kab. Tangerang\"}');
INSERT INTO `p_setting_item` VALUES (44, 2, 'Keluar', 0, 24, '{\"path_menu\":\"login/out\",\"icon_menu\":\"icon-logout.png\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (95, 2, 'Beranda', 0, 1, '{\"path_menu\":\"cmshome\",\"icon_menu\":\"icon-home.png\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (189, 11, 'Admin', 0, 1, '');
INSERT INTO `p_setting_item` VALUES (187, 11, 'Kabid. Telematika', 0, 2, '');
INSERT INTO `p_setting_item` VALUES (188, 11, 'Kasie e-Gov', 0, 3, '');
INSERT INTO `p_setting_item` VALUES (68, 3, '', 0, 0, '{\"id_menu\":\"44\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (73, 2, 'Setting', 0, 8, '{\"path_menu\":\"-\",\"icon_menu\":\"icon_settings.png\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (302, 7, 'statis', 0, 3, '{\"label\":\"Halaman Statis\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (74, 2, 'Pengguna', 73, 1, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (75, 2, 'Grup Pengguna', 74, 2, '{\"path_menu\":\"cmssetting/group\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (76, 2, 'Pengguna', 74, 1, '{\"path_menu\":\"cmssetting/user\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (81, 3, '', 0, 0, '{\"id_menu\":\"73\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (82, 3, '', 0, 0, '{\"id_menu\":\"74\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (83, 3, '', 0, 0, '{\"id_menu\":\"75\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (84, 3, '', 0, 0, '{\"id_menu\":\"76\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (300, 7, 'artikel', 0, 1, '{\"label\":\"Artikel\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (42, 1, 'Tutorial CSS', 38, 3, '{\"path_kanal\":\"tutorial_css\",\"path_root\":\"tutorial_website\",\"status\":\"on\",\"keterangan\":\"-\",\"tipe\":\"biasa\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (43, 1, 'Tutorial Codeigniter', 38, 4, '{\"path_kanal\":\"tutorial_codeigniter\",\"path_root\":\"tutorial_website\",\"status\":\"on\",\"keterangan\":\"-\",\"tipe\":\"biasa\",\"theme\":\"web\"}');
INSERT INTO `p_setting_item` VALUES (521, 2, 'Dashboard', 0, 2, '{\"path_menu\":\"module/appbkpp/dashboard\",\"icon_menu\":\"dashboard\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (421, 2, 'Penyusunan SKP', 0, 10, '{\"path_menu\":\"-\",\"icon_menu\":\"tasks\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (98, 12, 'Theme Default', 0, 0, '{\"theme_path\":\"web\",\"keterangan\":\"Theme Deafult CMS ini\",\"status\":\"on\",\"header_opsi\":{\"height\":\"75px\",\"margin_top\":\"0px\",\"margin_bottom\":\"0px\",\"padding_top\":\"10px\",\"padding_bottom\":\"0px\"}}');
INSERT INTO `p_setting_item` VALUES (101, 6, 'Teknologi Portalid', 0, 7, '{\"id_kanal\":\"3\",\"komponen\":\"artikel\",\"keterangan\":\"hkjh\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (121, 6, 'Pengantar', 0, 6, '{\"id_kanal\":\"3\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (123, 6, 'Mukadimah', 0, 4, '{\"id_kanal\":\"3\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (124, 6, 'Perkenalan', 0, 5, '{\"id_kanal\":\"43\",\"komponen\":\"artikel\",\"keterangan\":\"Berkenalan dengan Framework Codeigniter\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (125, 6, 'Membuat GridSystem Sendiri', 0, 4, '{\"id_kanal\":\"43\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"pending\"}');
INSERT INTO `p_setting_item` VALUES (126, 6, 'Membangun User Management', 0, 3, '{\"id_kanal\":\"43\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (127, 6, 'Form dan Validasi', 0, 2, '{\"id_kanal\":\"43\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (164, 6, 'Tentang Kami', 0, 1, '{\"id_kanal\":\"1\",\"komponen\":\"statis\",\"keterangan\":\"Halaman wajib\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (165, 6, 'Codeigniter HMVC', 0, 1, '{\"id_kanal\":\"43\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (161, 6, 'File Latihan HTML', 0, 2, '{\"id_kanal\":\"3\",\"komponen\":\"galeri\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (136, 6, 'Promo Produk', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (137, 6, 'Link Terkait', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (138, 6, 'Stop Press', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (139, 6, 'Iklan Layanan Masyarakat', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (140, 6, 'Dua', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (141, 6, 'Advertise Mainbar 01', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (142, 6, 'Advertise Mainbar Faktual', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (143, 6, 'Advertise Sub Sektor', 0, 0, '{\"id_kanal\":\"0\",\"komponen\":\"banner\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (151, 6, 'Ketentuan dan Syarat', 0, 3, '{\"id_kanal\":\"1\",\"komponen\":\"statis\",\"keterangan\":\"Syarat bertransaksi bisnis dengan kami\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (154, 6, 'Index Beranda', 0, 2, '{\"id_kanal\":\"1\",\"komponen\":\"statis\",\"keterangan\":\"Halaman suka suka\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (155, 6, 'Perkenalan', 0, 2, '{\"id_kanal\":\"40\",\"komponen\":\"artikel\",\"keterangan\":\"Berkenalan dengan HTML\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (156, 6, 'Perkenalan', 0, 1, '{\"id_kanal\":\"41\",\"komponen\":\"artikel\",\"keterangan\":\"Berkenalan dengan PHP dan MySQL\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (158, 6, 'Membuat Link', 0, 1, '{\"id_kanal\":\"40\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (157, 6, 'Perkenalan', 0, 1, '{\"id_kanal\":\"42\",\"komponen\":\"artikel\",\"keterangan\":\"Berkenalan dengan CSS\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (159, 6, 'Membuat Tabel', 0, 3, '{\"id_kanal\":\"40\",\"komponen\":\"artikel\",\"keterangan\":\"\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (160, 6, 'Perulangan', 0, 2, '{\"id_kanal\":\"41\",\"komponen\":\"artikel\",\"keterangan\":\"Teknik Looping dalam PHP\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (166, 6, 'Baru', 0, 1, '{\"id_kanal\":\"3\",\"komponen\":\"agenda\",\"keterangan\":\"askj\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (167, 6, 'Masjid', 0, 3, '{\"id_kanal\":\"3\",\"komponen\":\"direktori\",\"keterangan\":\"Rumah Ibadah Kaum Muslim\",\"status\":\"publish\", \"atribut\":[{\"label\":\"Alamat\"}, {\"label\":\"Luas Tanah\"}, {\"label\":\"Luas Bangunan\"}]}');
INSERT INTO `p_setting_item` VALUES (168, 6, 'Nature Mania', 0, 5, '{\"id_kanal\":\"3\",\"komponen\":\"galeri\",\"keterangan\":\"cobaa\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (169, 2, 'Website', 0, 7, '{\"path_menu\":\"-\",\"icon_menu\":\"icon_news.png\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (170, 2, 'Konten', 169, 1, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (171, 2, 'Artikel', 170, 1, '{\"path_menu\":\"cmsartikel\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (361, 9, 'Bohong', 0, 0, '{\"id_widget\":\"283\",\"id_kategori\":\"165,127\",\"keterangan\":\"hjh\"}');
INSERT INTO `p_setting_item` VALUES (405, 6, 'bh', 0, 1, '{\"id_kanal\":\"294\",\"komponen\":\"artikel\",\"keterangan\":\"dfd\",\"status\":\"publish\"}');
INSERT INTO `p_setting_item` VALUES (185, 2, 'Banner', 170, 7, '{\"path_menu\":\"cmsbanner\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (212, 9, 'Slider kanal Dokumentasi Portalid', 0, 0, '{\"id_widget\":\"264\",\"id_kategori\":\"123\",\"keterangan\":\"Untuk ditampilkan di kanal Dokumentasi Portalid\"}');
INSERT INTO `p_setting_item` VALUES (213, 9, 'Album Terkini', 0, 0, '{\"id_widget\":\"267\",\"id_kategori\":\"168,161\",\"keterangan\":\"Wrapper induk untuk dipasang di Halaman Utama / Detail\"}');
INSERT INTO `p_setting_item` VALUES (214, 9, 'Lebih dekat', 0, 0, '{\"id_widget\":\"267\",\"id_kategori\":\"168\",\"keterangan\":\"Wrapper khusus untuk rubrik LEBIH DEKAT\"}');
INSERT INTO `p_setting_item` VALUES (215, 9, 'Banner untuk kanal Beranda', 0, 0, '{\"id_widget\":\"268\",\"id_kategori\":\"136\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (216, 9, 'Artikel Terbaru', 0, 0, '{\"id_widget\":\"265\",\"id_kategori\":\"121,101\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (217, 9, 'Profil Emiten', 0, 0, '{\"id_widget\":\"269\",\"id_kategori\":\"\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (218, 9, 'Laporan Keuangan', 0, 0, '{\"id_widget\":\"270\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (219, 9, 'BEI at Glance', 0, 0, '{\"id_widget\":\"271\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (220, 9, 'Laporan Keuangan QoQ', 0, 0, '{\"id_widget\":\"272\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (221, 9, 'Laporan Keuangan YoY', 0, 0, '{\"id_widget\":\"273\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (222, 9, 'Best Fundamental Performers', 0, 0, '{\"id_widget\":\"274\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (223, 9, 'Agenda Terkini', 0, 0, '{\"id_widget\":\"275\",\"id_kategori\":\"131\",\"keterangan\":\"Untuk menapilkan Agenda Terbaru di Semua Rubrik Agenda Khusus untuk Halaman Utama / Beranda\"}');
INSERT INTO `p_setting_item` VALUES (224, 9, 'Agenda Terkini', 0, 0, '{\"id_widget\":\"275\",\"id_kategori\":\"131\",\"keterangan\":\"Untuk Menampilkan Wrapper Agenda khusus di kanal Profil Emiten\"}');
INSERT INTO `p_setting_item` VALUES (225, 9, 'Adv Mainbar', 0, 0, '{\"id_widget\":\"278\",\"id_kategori\":\"141\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (226, 9, 'Adv Faktual', 0, 0, '{\"id_widget\":\"278\",\"id_kategori\":\"142\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (227, 9, 'Adv Sub Sektor', 0, 0, '{\"id_widget\":\"278\",\"id_kategori\":\"143\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (228, 9, 'Contoh Wrapper', 0, 0, '{\"id_widget\":\"279\",\"id_kategori\":\"164\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (229, 9, 'Tutorial Codeigniter', 0, 0, '{\"id_widget\":\"280\",\"id_kategori\":\"165,124\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (230, 9, 'Index Beranda', 0, 0, '{\"id_widget\":\"281\",\"id_kategori\":\"154\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (231, 9, 'Tutorial HTML', 0, 0, '{\"id_widget\":\"280\",\"id_kategori\":\"158,155\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (232, 9, 'Tutorial PHP & MySQL', 0, 0, '{\"id_widget\":\"280\",\"id_kategori\":\"160,156\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (233, 9, 'Tutorial CSS', 0, 0, '{\"id_widget\":\"280\",\"id_kategori\":\"157\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (234, 9, 'Komentar n Polupuler 1', 0, 0, '{\"id_widget\":\"282\",\"id_kategori\":\"124,155,156,157\",\"keterangan\":\"Tab Utama/Beranda\"}');
INSERT INTO `p_setting_item` VALUES (235, 9, 'Percobaan', 0, 0, '{\"id_widget\":\"283\",\"id_kategori\":\"101\",\"keterangan\":\"Silder dari Lokomedia\"}');
INSERT INTO `p_setting_item` VALUES (236, 9, 'Master Calendar', 0, 0, '{\"id_widget\":\"284\",\"id_kategori\":\"166\",\"keterangan\":\"Calendar Utama\"}');
INSERT INTO `p_setting_item` VALUES (264, 8, 'artikel_slider', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"Menampilkan artikel terpilih dalam bentuk slider, biasanya setiap kanal ada slider artikelnya di bagian atas\",\"komponen\":\"artikel\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (265, 8, 'artikel_lastten', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Menampilkan 10 artikel terbaru, dalam bentuk judul dan potongan paragraf pertama\",\"komponen\":\"artikel\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"},{\"label\":\"Banyaknya berita\",\"nama\":\"n_item\",\"nilai\":\"3\"}]}');
INSERT INTO `p_setting_item` VALUES (266, 8, 'bukutamu', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Menampilkan komponen/rubrik bukutamu di kanal\",\"komponen\":\"bukutamu\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (267, 8, 'galeri', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Menampilkan komponen galeri di kanal\",\"komponen\":\"galeri\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (268, 8, 'banner_slider', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"Menampilkan gambar di kanal\",\"komponen\":\"banner\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (269, 8, 'profil_emiten', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"Untuk menampilkan daftar emiten menurut kategori sektor dan sub-sektor\",\"komponen\":\"profil_emiten\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (270, 8, 'laporan_keuangan', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"Untuk menampilkan data aktual laporan keuangan emiten per kwartal\",\"komponen\":\"laporan_keuangan\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (271, 8, 'atglance', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Untuk menampilkan data BEI at Glance\",\"komponen\":\"atglance\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (272, 8, 'laporan_keuanganqoq', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"-\",\"komponen\":\"\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (273, 8, 'laporan_keuanganyoy', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"-\",\"komponen\":\"laporan_keuanganyoy\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (274, 8, 'best_fundamental', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"-\",\"komponen\":\"best_fundamental\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (275, 8, 'agenda', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"-\",\"komponen\":\"agenda\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (276, 8, 'direktori', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"-\",\"komponen\":\"direktori\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (277, 8, 'daftar', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"Type Direktori Langsung\",\"komponen\":\"direktori\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"},{\"label\":\"Banyaknya item\",\"nama\":\"n_item\",\"nilai\":\"2\"}]}');
INSERT INTO `p_setting_item` VALUES (278, 8, 'banner_main', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Banner Slider untuk ditampilkan di Mainbar\",\"komponen\":\"banner\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (279, 8, 'statis', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"-\",\"komponen\":\"statis\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (280, 8, 'index_tutorial', 0, 0, '{\"lokasi_widget\":\"topbar\",\"keterangan\":\"-\",\"komponen\":\"artikel\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (281, 8, 'statis_main', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"bg\",\"komponen\":\"statis\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (282, 8, 'commented', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"df\",\"komponen\":\"artikel\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (283, 8, 'hl_slider', 0, 0, '{\"lokasi_widget\":\"mainbar\",\"keterangan\":\"Widget anu\",\"komponen\":\"artikel\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (284, 8, 'calendar', 0, 0, '{\"lokasi_widget\":\"sidebar\",\"keterangan\":\"Kalender agenda dari Bang Opik\",\"komponen\":\"agenda\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}');
INSERT INTO `p_setting_item` VALUES (285, 2, 'Menu Administrator', 73, 2, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (286, 3, '', 0, 0, '{\"id_menu\":\"285\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (287, 2, 'Menu Pengguna', 285, 1, '{\"path_menu\":\"cmssetting/menu_pengguna\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (288, 2, 'Menu', 285, 2, '{\"path_menu\":\"cmssetting/menu\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (289, 3, '', 0, 0, '{\"id_menu\":\"287\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (290, 3, '', 0, 0, '{\"id_menu\":\"288\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (301, 7, 'galeri', 0, 2, '{\"label\":\"Galeri\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (192, 11, 'sdf kasasi', 0, 5, '');
INSERT INTO `p_setting_item` VALUES (190, 11, 'Staf', 0, 6, '');
INSERT INTO `p_setting_item` VALUES (308, 2, 'Setting Utama', 307, 1, '{\"path_menu\":\"cmssetting\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (309, 2, 'Master Widget', 307, 2, '{\"path_menu\":\"cmssetting/widget\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (321, 2, 'Kanal', 169, 3, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (322, 2, 'Rubrik', 321, 1, '{\"path_menu\":\"cmssetting/kategori\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (323, 2, 'Kanal', 321, 2, '{\"path_menu\":\"cmssetting/kanal\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (390, 10, 'topbar', 0, 0, '{\"id_kanal\":\"1\",\"path_kanal\":\"\",\"widget\":[{\"nama_widget\":\"artikel_slider\",\"id_widget\":\"264\",\"id_wrapper\":\"212\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"0px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (393, 10, 'mainbar', 0, 0, '{\"id_kanal\":\"1\",\"path_kanal\":\"\",\"widget\":[{\"nama_widget\":\"statis_main\",\"id_widget\":\"281\",\"id_wrapper\":\"230\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"30px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}, {\"nama_widget\":\"banner_main\",\"id_widget\":\"278\",\"id_wrapper\":\"226\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"20px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}, {\"nama_widget\":\"artikel_lastten\",\"id_widget\":\"265\",\"id_wrapper\":\"216\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"},{\"label\":\"Banyaknya berita\",\"nama\":\"n_item\",\"nilai\":\"4\"}]}, {\"nama_widget\":\"galeri\",\"id_widget\":\"267\",\"id_wrapper\":\"213\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (329, 10, 'sidebar', 0, 0, '{\"id_kanal\":\"1\",\"path_kanal\":\"\",\"widget\":[{\"nama_widget\":\"daftar\",\"id_widget\":\"277\",\"id_wrapper\":\"408\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"},{\"label\":\"Banyaknya item\",\"nama\":\"n_item\",\"nilai\":\"2\"}]},{\"nama_widget\":\"banner_slider\",\"id_widget\":\"268\",\"id_wrapper\":\"387\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]},{\"nama_widget\":\"commented\",\"id_widget\":\"282\",\"id_wrapper\":\"234\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]},{\"nama_widget\":\"calendar\",\"id_widget\":\"284\",\"id_wrapper\":\"236\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (330, 10, 'topbar', 0, 0, '{\"id_kanal\":\"38\",\"path_kanal\":\"tutorial_website\",\"widget\":[{\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"231\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}, {\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"232\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}, {\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"233\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}, {\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"229\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (331, 10, 'topbar', 0, 0, '{\"id_kanal\":\"40\",\"path_kanal\":\"tutorial_html\",\"widget\":[{\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"231\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"20px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (332, 10, 'topbar', 0, 0, '{\"id_kanal\":\"42\",\"path_kanal\":\"tutorial_css\",\"widget\":[{\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"233\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (333, 10, 'topbar', 0, 0, '{\"id_kanal\":\"41\",\"path_kanal\":\"tutorial_php___mysql\",\"widget\":[{\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"232\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (334, 10, 'topbar', 0, 0, '{\"id_kanal\":\"43\",\"path_kanal\":\"tutorial_codeigniter\",\"widget\":[{\"nama_widget\":\"index_tutorial\",\"id_widget\":\"280\",\"id_wrapper\":\"229\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (335, 10, 'mainbar', 0, 0, '{\"id_kanal\":\"3\",\"path_kanal\":\"dokumentasi_portalid\",\"widget\":[{\"nama_widget\":\"hl_slider\",\"id_widget\":\"283\",\"id_wrapper\":\"235\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}, {\"nama_widget\":\"artikel_lastten\",\"id_widget\":\"265\",\"id_wrapper\":\"216\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"},{\"label\":\"Banyaknya berita\",\"nama\":\"n_item\",\"nilai\":\"3\"}]}, {\"nama_widget\":\"banner_main\",\"id_widget\":\"278\",\"id_wrapper\":\"227\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}, {\"nama_widget\":\"galeri\",\"id_widget\":\"267\",\"id_wrapper\":\"214\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"10px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (336, 10, 'sidebar', 0, 0, '{\"id_kanal\":\"3\",\"path_kanal\":\"dokumentasi_portalid\",\"widget\":[{\"nama_widget\":\"banner_slider\",\"id_widget\":\"268\",\"id_wrapper\":\"215\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}, {\"nama_widget\":\"commented\",\"id_widget\":\"282\",\"id_wrapper\":\"234\",\"opsi\":[{\"label\":\"Margin atas\",\"nama\":\"margin_top\",\"nilai\":\"10px\"},{\"label\":\"Margin bawah\",\"nama\":\"margin_bottom\",\"nilai\":\"0px\"}]}]}');
INSERT INTO `p_setting_item` VALUES (338, 2, 'Agenda', 170, 4, '{\"path_menu\":\"cmsagenda\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (339, 2, 'Direktori', 170, 6, '{\"path_menu\":\"cmsdirektori\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (340, 2, 'Halaman Statis', 170, 2, '{\"path_menu\":\"cmsstatis\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (341, 2, 'Galeri', 170, 3, '{\"path_menu\":\"cmsgaleri\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (342, 2, 'Polling', 170, 5, '{\"path_menu\":\"cmspolling\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (343, 2, 'Sekilas Info', 170, 8, '{\"path_menu\":\"cmssekilasinfo\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (350, 2, 'Tampilan', 169, 2, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (351, 2, 'Wrapper Kanal', 350, 1, '{\"path_menu\":\"cmssetting/wrapper_kanal\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (352, 2, 'Wrapper', 350, 2, '{\"path_menu\":\"cmssetting/wrapper\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (191, 11, 'Operator', 0, 4, '');
INSERT INTO `p_setting_item` VALUES (367, 2, 'Ganti Password', 74, 3, '{\"path_menu\":\"cmssetting/user/password\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (368, 3, '', 0, 0, '{\"id_menu\":\"367\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (380, 7, 'direktori', 0, 4, '{\"label\":\"Direktori\",\"custom\":\"cmsdirektori/tambah_atribut\"}');
INSERT INTO `p_setting_item` VALUES (381, 7, 'polling', 0, 5, '{\"label\":\"Polling\",\"custom\":\"cmspolling/tambah_pilihan\"}');
INSERT INTO `p_setting_item` VALUES (382, 7, 'banner', 0, 6, '{\"label\":\"Banner\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (383, 7, 'agenda', 0, 7, '{\"label\":\"Agenda\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (384, 7, 'info', 0, 8, '{\"label\":\"Sekilas Info\",\"custom\":\"\"}');
INSERT INTO `p_setting_item` VALUES (4, 4, 'superadmin', 0, 0, '{\"section_name\":\"cp\",\"back_office\":\"cp\",\"keterangan\":\"\"}');
INSERT INTO `p_setting_item` VALUES (5, 4, 'admin', 0, 0, '{\"section_name\":\"admin\",\"back_office\":\"admin\",\"keterangan\":\"\"}');
INSERT INTO `p_setting_item` VALUES (598, 4, 'penggajian', 0, 0, '{\"section_name\":\"penggajian\",\"back_office\":\"admin\",\"keterangan\":\"Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (599, 3, '', 0, 0, '{\"id_menu\":\"498\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (387, 9, 'Iklan', 0, 0, '{\"id_widget\":\"268\",\"id_kategori\":\"139\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (99, 12, 'Theme Alternatif', 0, 0, '{\"theme_path\":\"web_alt\",\"keterangan\":\"Theme Alternatif CMS ini\",\"status\":\"on\"}');
INSERT INTO `p_setting_item` VALUES (128, 13, 'header', 0, 0, '{\"path_kanal\":\"dokumentasi_portalid\",\"judul_header\":\"Dokumentasi Portalid\",\"sub_judul\":\"Portalid - Simplify the Complexity\",\"height\":\"75px\",\"margin_top\":\"10px\",\"margin_bottom\":\"0px\",\"padding_top\":\"0px\",\"padding_bottom\":\"0px\"}');
INSERT INTO `p_setting_item` VALUES (129, 13, 'header', 0, 0, '{\"path_kanal\":\"\",\"judul_header\":\"Portalid\",\"sub_judul\":\"Simplify the Complexity\",\"height\":\"75px\",\"margin_top\":\"0px\",\"margin_bottom\":\"0px\",\"padding_top\":\"10px\",\"padding_bottom\":\"0px\"}');
INSERT INTO `p_setting_item` VALUES (389, 13, 'header', 0, 0, '{\"path_kanal\":\"tutorial_website\",\"judul_header\":\"Tutorial Website\",\"sub_judul\":\"Portalid - Simplify the Complexity\",\"height\":\"75px\",\"margin_top\":\"0px\",\"margin_bottom\":\"0px\",\"padding_top\":\"10px\",\"padding_bottom\":\"0px\"}');
INSERT INTO `p_setting_item` VALUES (408, 9, 'Daftar masjid', 0, 0, '{\"id_widget\":\"277\",\"id_kategori\":\"167\",\"keterangan\":\"nmn\"}');
INSERT INTO `p_setting_item` VALUES (409, 13, 'header', 0, 0, '{\"path_kanal\":\"tutorial_html\",\"judul_header\":\"HTML\",\"sub_judul\":\"Kuda\",\"height\":\"75px\",\"margin_top\":\"0px\",\"margin_bottom\":\"0px\",\"padding_top\":\"10px\",\"padding_bottom\":\"0px\"}');
INSERT INTO `p_setting_item` VALUES (422, 2, 'Target Kinerja', 421, 1, '{\"path_menu\":\"module/appskp/skp\",\"icon_menu\":\"bullseye\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (418, 2, 'Dashboard', 0, 3, '{\"path_menu\":\"module/appbkpp/dashboard/pegawai\",\"icon_menu\":\"dashboard\",\"keterangan\":\"KHUSUS CMS SB_ADMIN\"}');
INSERT INTO `p_setting_item` VALUES (438, 3, '', 0, 0, '{\"id_menu\":\"422\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (439, 3, '', 0, 0, '{\"id_menu\":\"427\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (427, 2, 'Realisasi Kinerja', 421, 2, '{\"path_menu\":\"module/appskp/realisasi\",\"icon_menu\":\"support\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (429, 2, 'Persetujuan SKP', 0, 11, '{\"path_menu\":\"-\",\"icon_menu\":\"check-square-o\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (430, 2, 'Target Kinerja', 429, 1, '{\"path_menu\":\"module/appskp/skp_kelola\",\"icon_menu\":\"bullseye\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (431, 2, 'Realisasi Kinerja', 429, 2, '{\"path_menu\":\"module/appskp/realisasi_kelola\",\"icon_menu\":\"support\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (436, 3, '', 0, 0, '{\"id_menu\":\"418\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (437, 3, '', 0, 0, '{\"id_menu\":\"421\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (463, 2, 'Daftar Jabatan Fungsional', 447, 2, '{\"path_menu\":\"module/appbkpp/jabfung\",\"icon_menu\":\"wrench\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (443, 2, 'Data Pegawai', 0, 9, '{\"path_menu\":\"module/appbkpp/profile\",\"icon_menu\":\"users\",\"keterangan\":\"Khusus untuk Group Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (440, 3, '', 0, 0, '{\"id_menu\":\"429\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (441, 3, '', 0, 0, '{\"id_menu\":\"430\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (442, 3, '', 0, 0, '{\"id_menu\":\"431\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (444, 3, '', 0, 0, '{\"id_menu\":\"443\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (480, 2, 'Dashboard', 0, 4, '{\"path_menu\":\"module/appbkpp/dashboard/umpeg\",\"icon_menu\":\"dashboard\",\"keterangan\":\"Khusus untuk pengelola Kepegawaian\"}');
INSERT INTO `p_setting_item` VALUES (447, 2, 'Referensi', 0, 12, '{\"path_menu\":\"-\",\"icon_menu\":\"check-square-o\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (448, 3, '', 0, 0, '{\"id_menu\":\"447\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (449, 2, 'Daftar Pendidikan Formal', 447, 3, '{\"path_menu\":\"module/appbkpp/pendidikan\",\"icon_menu\":\"graduation-cap\",\"keterangan\":\"Khusus SB ADMIN\"}');
INSERT INTO `p_setting_item` VALUES (450, 3, '', 0, 0, '{\"id_menu\":\"449\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (451, 2, 'Daftar Pemangku Jabatan', 447, 4, '{\"path_menu\":\"module/appbkpp/pejabat\",\"icon_menu\":\"hand-o-right\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (452, 3, '', 0, 0, '{\"id_menu\":\"451\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (453, 2, 'Tupoksi', 447, 5, '{\"path_menu\":\"module/appskp/tupoksi\",\"icon_menu\":\"cubes\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (556, 2, 'Mutasi Pegawai', 0, 21, '{\"path_menu\":\"module/appbkpp/mutasi\",\"icon_menu\":\"refresh\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (455, 2, 'Tarif TPP', 447, 6, '{\"path_menu\":\"module/appskp/tarif\",\"icon_menu\":\"calculator\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (538, 2, 'Laporan', 0, 22, '{\"path_menu\":\"-\",\"icon_menu\":\"file-text\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (467, 2, 'Daftar Pegawai', 0, 14, '{\"path_menu\":\"module/appbkpp/pegawai/aktif\",\"icon_menu\":\"users\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (468, 3, '', 0, 0, '{\"id_menu\":\"467\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (459, 2, 'Ganti password', 0, 23, '{\"path_menu\":\"module/appskp/sett/ganti_password\",\"icon_menu\":\"lock\",\"keterangan\":\"untuk sb-2\"}');
INSERT INTO `p_setting_item` VALUES (460, 3, '', 0, 0, '{\"id_menu\":\"459\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (600, 2, 'Referensi', 0, 26, '{\"path_menu\":\"#\",\"icon_menu\":\"gear\",\"keterangan\":\"Menu Referensi Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (464, 3, '', 0, 0, '{\"id_menu\":\"463\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (465, 2, 'Daftar Unit Kerja', 447, 1, '{\"path_menu\":\"module/appbkpp/unor\",\"icon_menu\":\"list\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (466, 3, '', 0, 0, '{\"id_menu\":\"465\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (469, 2, 'Mutasi Pegawai', 0, 15, '{\"path_menu\":\"module/appbkpp/mutasi\",\"icon_menu\":\"refresh\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (471, 2, 'Pemantauan SKP', 0, 16, '{\"path_menu\":\"module/appskp/sett/pantau_target\",\"icon_menu\":\"indent\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (473, 3, '', 0, 0, '{\"id_menu\":\"459\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (474, 2, 'Setting Pengguna', 0, 19, '{\"path_menu\":\"module/appskp/sett/pengelola\",\"icon_menu\":\"link\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (476, 3, '', 0, 0, '{\"id_menu\":\"467\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (481, 3, '', 0, 0, '{\"id_menu\":\"480\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (482, 3, '', 0, 0, '{\"id_menu\":\"469\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (483, 3, '', 0, 0, '{\"id_menu\":\"447\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (484, 3, '', 0, 0, '{\"id_menu\":\"465\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (485, 3, '', 0, 0, '{\"id_menu\":\"463\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (486, 3, '', 0, 0, '{\"id_menu\":\"449\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (487, 3, '', 0, 0, '{\"id_menu\":\"451\",\"group_id\":\"6\"}');
INSERT INTO `p_setting_item` VALUES (489, 2, 'Dashboard', 0, 5, '{\"path_menu\":\"module/appbkpp/dashboard/mutasi\",\"icon_menu\":\"dashboard\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (490, 3, '', 0, 0, '{\"id_menu\":\"489\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (491, 3, '', 0, 0, '{\"id_menu\":\"467\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (492, 3, '', 0, 0, '{\"id_menu\":\"447\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (493, 3, '', 0, 0, '{\"id_menu\":\"465\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (494, 3, '', 0, 0, '{\"id_menu\":\"463\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (495, 3, '', 0, 0, '{\"id_menu\":\"449\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (496, 3, '', 0, 0, '{\"id_menu\":\"451\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (497, 2, 'Tools', 0, 13, '{\"path_menu\":\"-\",\"icon_menu\":\"wrench\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (498, 2, 'Dashboard', 0, 6, '{\"path_menu\":\"module/apppenggajian/dashboard/index\",\"icon_menu\":\"dashboard\",\"keterangan\":\"Dashboard Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (499, 3, '', 0, 0, '{\"id_menu\":\"498\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (500, 2, 'Verifikasi SKP', 0, 17, '{\"path_menu\":\"-\",\"icon_menu\":\"tasks\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (501, 2, 'Target Kinerja', 500, 1, '{\"path_menu\":\"module/appskp/skp_verifikasi\",\"icon_menu\":\"bullseye\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (502, 3, '', 0, 0, '{\"id_menu\":\"500\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (503, 3, '', 0, 0, '{\"id_menu\":\"501\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (504, 2, 'Realisasi Kinerja', 500, 2, '{\"path_menu\":\"module/appskp/realisasi_verifikasi\",\"icon_menu\":\"support\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (505, 3, '', 0, 0, '{\"id_menu\":\"504\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (506, 2, 'Informasi Verifikatur', 0, 18, '{\"path_menu\":\"-\",\"icon_menu\":\"bell\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (507, 2, 'Daftar Unit Kerja', 506, 1, '{\"path_menu\":\"module/appskp/verifikatur/unor\",\"icon_menu\":\"sitemap\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (508, 3, '', 0, 0, '{\"id_menu\":\"506\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (509, 3, '', 0, 0, '{\"id_menu\":\"507\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (510, 2, 'Arsip SKP Terverifikasi', 506, 2, '{\"path_menu\":\"module/appskp/verifikatur/arsip\",\"icon_menu\":\"save\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (511, 3, '', 0, 0, '{\"id_menu\":\"510\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (512, 3, '', 0, 0, '{\"id_menu\":\"459\",\"group_id\":\"477\"}');
INSERT INTO `p_setting_item` VALUES (513, 2, 'Rancangan Mutasi', 497, 1, '{\"path_menu\":\"module/appbkpp/mutasi/rancangan\",\"icon_menu\":\"recycle\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (514, 2, 'Mutasi Pegawai', 497, 2, '{\"path_menu\":\"module/appbkpp/mutasi\",\"icon_menu\":\"refresh\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (515, 3, '', 0, 0, '{\"id_menu\":\"497\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (516, 3, '', 0, 0, '{\"id_menu\":\"513\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (517, 3, '', 0, 0, '{\"id_menu\":\"514\",\"group_id\":\"488\"}');
INSERT INTO `p_setting_item` VALUES (522, 3, '', 0, 0, '{\"id_menu\":\"521\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (523, 2, 'Cetak Penilaian', 0, 20, '{\"path_menu\":\"module/appskp/penilaian\",\"icon_menu\":\"print\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (524, 3, '', 0, 0, '{\"id_menu\":\"523\",\"group_id\":\"7\"}');
INSERT INTO `p_setting_item` VALUES (540, 2, 'Jabatan', 538, 2, '{\"path_menu\":\"module/laporan/sett/jabatan\",\"icon_menu\":\"tasks fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (539, 2, 'Kepangkatan', 538, 1, '{\"path_menu\":\"module/laporan/sett/kepangkatan\",\"icon_menu\":\"signal fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (541, 2, 'Sanksi', 538, 3, '{\"path_menu\":\"module/laporan/sett/sanksi\",\"icon_menu\":\"exclamation fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (542, 2, 'Penghargaan', 538, 4, '{\"path_menu\":\"module/laporan/sett/penghargaan\",\"icon_menu\":\"tags fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (543, 2, 'Kesehatan', 538, 5, '{\"path_menu\":\"module/laporan/sett/kesehatan\",\"icon_menu\":\"stethoscope fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (544, 2, 'Psikotes', 538, 6, '{\"path_menu\":\"module/laporan/sett/psikotes\",\"icon_menu\":\"ticket  fa\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (545, 2, 'Pengalaman', 538, 7, '{\"path_menu\":\"module/laporan/sett/pengalaman\",\"icon_menu\":\"list\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (546, 3, '', 0, 0, '{\"id_menu\":\"538\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (547, 3, '', 0, 0, '{\"id_menu\":\"539\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (548, 3, '', 0, 0, '{\"id_menu\":\"540\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (549, 3, '', 0, 0, '{\"id_menu\":\"541\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (550, 3, '', 0, 0, '{\"id_menu\":\"542\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (551, 3, '', 0, 0, '{\"id_menu\":\"543\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (552, 3, '', 0, 0, '{\"id_menu\":\"544\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (553, 3, '', 0, 0, '{\"id_menu\":\"545\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (554, 2, 'Diklat', 538, 8, '{\"path_menu\":\"module/laporan/sett/diklat\",\"icon_menu\":\"graduation-cap\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (555, 3, '', 0, 0, '{\"id_menu\":\"554\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (557, 3, '', 0, 0, '{\"id_menu\":\"556\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (571, 2, 'Setting', 0, 25, '{\"path_menu\":\"-\",\"icon_menu\":\"link\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (572, 2, 'Pengguna', 571, 1, '{\"path_menu\":\"module/appbkpp/user\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (573, 2, 'Menu Administrator', 571, 2, '{\"path_menu\":\"-\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (577, 2, 'Menu Pengguna', 573, 1, '{\"path_menu\":\"module/appbkpp/menu_pengguna\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (578, 2, 'Menu', 573, 2, '{\"path_menu\":\"module/appbkpp/menu\",\"icon_menu\":\"-\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (601, 2, 'Masa Kerja', 600, 1, '{\"path_menu\":\"module/apppenggajian/masa_kerja\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Rerefensi Masa kerja modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (602, 2, 'Gaji Pokok', 600, 2, '{\"path_menu\":\"module/apppenggajian/gaji_pokok\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi Gaji Pokok Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (603, 2, 'Tunjangan Kelompok', 600, 3, '{\"path_menu\":\"module/apppenggajian/tunjangan_kelompok\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi Tunjangan Kelompok Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (604, 2, 'Tunjangan Jenis', 600, 4, '{\"path_menu\":\"module/apppenggajian/tunjangan_jenis\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi Tunjangan Jenis Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (605, 2, 'Potongan Jenis', 600, 5, '{\"path_menu\":\"module/apppenggajian/potongan_jenis\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi Potongan Jenis Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (606, 2, 'Peraturan Gaji', 600, 6, '{\"path_menu\":\"module/apppenggajian/peraturan_gaji\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi Peraturan Gaji Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (607, 2, 'PPh 21', 600, 7, '{\"path_menu\":\"module/apppenggajian/pph21\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Referensi PPh 21 Modul Pengggajian\"}');
INSERT INTO `p_setting_item` VALUES (608, 2, 'Pendapatan Lain', 600, 8, '{\"path_menu\":\"module/apppenggajian/pendapatan_lain\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu referensi Pendapatan Lain Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (609, 2, 'Pendapatan Lain', 600, 9, '{\"path_menu\":\"#\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu referensi Pendapatan Lain Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (610, 2, 'Perhitungan PPh 21', 0, 27, '{\"path_menu\":\"#\",\"icon_menu\":\"gear\",\"keterangan\":\"Menu Perhitungan PPh 21 Modul penggajian\"}');
INSERT INTO `p_setting_item` VALUES (611, 2, 'Perhitungan Gaji Pegawai', 0, 28, '{\"path_menu\":\"#\",\"icon_menu\":\"gear\",\"keterangan\":\"Menu Perhitungan Gaji Pegawai Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (612, 2, 'Daftar Pegawai', 0, 29, '{\"path_menu\":\"module/apppenggajian/pegawai/aktif\",\"icon_menu\":\"users\",\"keterangan\":\"Menu Daftar Pegawai Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (613, 2, 'Daftar Gaji Pegawai', 0, 30, '{\"path_menu\":\"#\",\"icon_menu\":\"gear\",\"keterangan\":\"Menu Daftar Gaji Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (614, 2, 'Riwayat Gaji Pegawai', 613, 1, '{\"path_menu\":\"#\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Daftar Gaji Pegawai , Riwayat Gaji Pegawai Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (615, 2, 'Rincian Data Pegawai', 613, 2, '{\"path_menu\":\"#\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Rincian data Pegawai Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (616, 2, 'Laporan', 0, 31, '{\"path_menu\":\"#\",\"icon_menu\":\"gear\",\"keterangan\":\"Menu Laporan Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (617, 2, 'Gaji Bulanan Pegawai', 616, 1, '{\"path_menu\":\"#\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Gaji Bulanan Pegawai Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (618, 2, 'Rincian Gaji Tahuanan', 616, 2, '{\"path_menu\":\"#\",\"icon_menu\":\"caret-right\",\"keterangan\":\"Menu Rincian Gaji Tahuanan Modul Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (619, 3, '', 0, 0, '{\"id_menu\":\"600\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (620, 3, '', 0, 0, '{\"id_menu\":\"601\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (621, 3, '', 0, 0, '{\"id_menu\":\"602\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (622, 3, '', 0, 0, '{\"id_menu\":\"603\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (623, 3, '', 0, 0, '{\"id_menu\":\"604\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (624, 3, '', 0, 0, '{\"id_menu\":\"605\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (625, 3, '', 0, 0, '{\"id_menu\":\"606\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (626, 3, '', 0, 0, '{\"id_menu\":\"607\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (627, 3, '', 0, 0, '{\"id_menu\":\"608\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (628, 3, '', 0, 0, '{\"id_menu\":\"610\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (629, 3, '', 0, 0, '{\"id_menu\":\"611\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (630, 3, '', 0, 0, '{\"id_menu\":\"612\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (631, 3, '', 0, 0, '{\"id_menu\":\"613\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (632, 3, '', 0, 0, '{\"id_menu\":\"614\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (633, 3, '', 0, 0, '{\"id_menu\":\"615\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (634, 3, '', 0, 0, '{\"id_menu\":\"616\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (635, 3, '', 0, 0, '{\"id_menu\":\"617\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (636, 3, '', 0, 0, '{\"id_menu\":\"618\",\"group_id\":\"598\"}');
INSERT INTO `p_setting_item` VALUES (667, 2, 'Daftar Tunjangan', 661, 1, '{\"path_menu\":\"apppayroll/ref_allowance/index\",\"icon_menu\":\"fa fa-life-ring fa-fw\",\"keterangan\":\"Pay Roll App - Daftar Tunjangan\"}');
INSERT INTO `p_setting_item` VALUES (640, 3, '', 0, 0, '{\"id_menu\":\"639\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (641, 2, 'Referensi', 0, 39, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-cogs fa-fw\",\"keterangan\":\"Pay Roll App - Referensi\"}');
INSERT INTO `p_setting_item` VALUES (642, 3, '', 0, 0, '{\"id_menu\":\"641\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (643, 2, 'Gaji Pokok Pegawai', 675, 2, '{\"path_menu\":\"apppayroll/ref_base_salary/index\",\"icon_menu\":\"fa fa-newspaper-o fa-fw\",\"keterangan\":\"Pay Roll App - Gaji Pokok\"}');
INSERT INTO `p_setting_item` VALUES (644, 3, '', 0, 0, '{\"id_menu\":\"643\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (645, 2, 'Dokumen Legal', 641, 8, '{\"path_menu\":\"apppayroll/legal/index\",\"icon_menu\":\"fa fa-file fa-fw\",\"keterangan\":\"Pay Roll App - Dokumen Legal\"}');
INSERT INTO `p_setting_item` VALUES (695, 2, 'Absensi', 675, 3, '{\"path_menu\":\"apppayroll/adm_attn/index\",\"icon_menu\":\"fa fa-calendar-o\",\"keterangan\":\"Pay Roll App - Administrasi Absensi\"}');
INSERT INTO `p_setting_item` VALUES (647, 2, 'Kepegawaian', 0, 36, '{\"path_menu\":\"apppayroll/employee/index\",\"icon_menu\":\"fa fa-user fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi Kepegawaian\"}');
INSERT INTO `p_setting_item` VALUES (649, 2, 'Olah Data', 643, 1, '{\"path_menu\":\"apppayroll/ref_base_salary/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Gaji Pokok\"}');
INSERT INTO `p_setting_item` VALUES (654, 2, 'Data Induk', 647, 1, '{\"path_menu\":\"apppayroll/employee/master\",\"icon_menu\":\"fa fa-user fa-fw\",\"keterangan\":\"Menu Data Induk Pegawai Pay Roll App\"}');
INSERT INTO `p_setting_item` VALUES (656, 2, 'Slip Gaji', 0, 34, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-money fa-fw\",\"keterangan\":\"Pay Roll App - Slip Gaji Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (657, 3, '', 0, 0, '{\"id_menu\":\"656\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (658, 2, 'Laporan', 0, 38, '{\"path_menu\":\"apppayroll/report/index\",\"icon_menu\":\"fa fa-tasks fa-fw\",\"keterangan\":\"Pay Roll App - Laporan Administrasi Gaji\"}');
INSERT INTO `p_setting_item` VALUES (661, 2, 'Tunjangan', 641, 4, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-life-ring fa-fw\",\"keterangan\":\"Pay Roll App - Menu Referensi Tunjangan\"}');
INSERT INTO `p_setting_item` VALUES (659, 3, '', 0, 0, '{\"id_menu\":\"658\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (660, 3, '', 0, 0, '{\"id_menu\":\"649\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (662, 3, '', 0, 0, '{\"id_menu\":\"661\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (663, 2, 'Tambah', 645, 1, '{\"path_menu\":\"apppayroll/legal/add\",\"icon_menu\":\"fa fa-plus fa-fw\",\"keterangan\":\"Pay Roll App - Dokumen Legal - Tambah\"}');
INSERT INTO `p_setting_item` VALUES (665, 2, 'Sunting', 645, 2, '{\"path_menu\":\"apppayroll/legal/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Dokumen Legal - Sunting\"}');
INSERT INTO `p_setting_item` VALUES (696, 2, 'Olah Data Absensi', 695, 1, '{\"path_menu\":\"apppayroll/adm_attn/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi Absensi\"}');
INSERT INTO `p_setting_item` VALUES (668, 3, '', 0, 0, '{\"id_menu\":\"667\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (669, 2, 'Daftar Transfer BJB', 658, 1, '{\"path_menu\":\"apppayroll/report/ibl_bjb\",\"icon_menu\":\"fa fa-university fa-fw\",\"keterangan\":\"Pay Roll App - Daftar Transfer BJB\"}');
INSERT INTO `p_setting_item` VALUES (671, 2, 'Koperasi', 641, 7, '{\"path_menu\":\"apppayroll/ref_wk_coopr/index\",\"icon_menu\":\"fa fa-sitemap fa-fw\",\"keterangan\":\"Pay Roll App - Pengaturan Koperasi Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (677, 3, '', 0, 0, '{\"id_menu\":\"675\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (679, 2, 'Zakat & Shodaqoh', 675, 8, '{\"path_menu\":\"apppayroll/zkt_sh/index\",\"icon_menu\":\"fa fa-users fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi Zakat & Shodaqoh\"}');
INSERT INTO `p_setting_item` VALUES (675, 2, 'Administrasi', 0, 37, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-pencil fa-fw\",\"keterangan\":\"Pay Roll App - Menu Administrasi\"}');
INSERT INTO `p_setting_item` VALUES (676, 2, 'Koperasi Pegawai', 776, 6, '{\"path_menu\":\"apppayroll/adm_wc/index\",\"icon_menu\":\"fa fa-sitemap fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi Koperasi Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (678, 3, '', 0, 0, '{\"id_menu\":\"676\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (710, 2, 'Anggota', 708, 1, '{\"path_menu\":\"apppayroll/adm_dw/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Anggota Dharma Wanita\"}');
INSERT INTO `p_setting_item` VALUES (681, 2, 'Olah Data', 679, 1, '{\"path_menu\":\"apppayroll/zkt_sh/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Zakat & Shodaqoh\"}');
INSERT INTO `p_setting_item` VALUES (683, 2, 'TPP', 772, 8, '{\"path_menu\":\"apppayroll/adm_tpp/index\",\"icon_menu\":\"fa fa-calculator\",\"keterangan\":\"Pay Roll App - Administrasi TPP\"}');
INSERT INTO `p_setting_item` VALUES (684, 3, '', 0, 0, '{\"id_menu\":\"683\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (685, 2, 'Olah Data', 683, 1, '{\"path_menu\":\"apppayroll/adm_tpp/edit\",\"icon_menu\":\"fa fa-edit\",\"keterangan\":\"Pay Roll App - Olah Data TPP\"}');
INSERT INTO `p_setting_item` VALUES (686, 3, '', 0, 0, '{\"id_menu\":\"685\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (687, 2, 'Potongan', 641, 5, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-crop fa-fw\",\"keterangan\":\"Pay Roll App - Menu Referensi Potongan\"}');
INSERT INTO `p_setting_item` VALUES (688, 2, 'Daftar Potongan', 687, 1, '{\"path_menu\":\"apppayroll/ref_deduction/index\",\"icon_menu\":\"fa fa-crop fa-fw\",\"keterangan\":\"Pay Roll App - Daftar Potongan\"}');
INSERT INTO `p_setting_item` VALUES (689, 3, '', 0, 0, '{\"id_menu\":\"687\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (690, 3, '', 0, 0, '{\"id_menu\":\"688\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (691, 2, 'Olah Data Potongan', 688, 1, '{\"path_menu\":\"apppayroll/ref_deduction/edit\",\"icon_menu\":\"fa fa-edit\",\"keterangan\":\"Pay Roll App - Olah Data Potongan\"}');
INSERT INTO `p_setting_item` VALUES (692, 3, '', 0, 0, '{\"id_menu\":\"691\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (693, 2, 'Olah Data Tunjangan', 667, 1, '{\"path_menu\":\"apppayroll/ref_allowance/edit\",\"icon_menu\":\"fa fa-pencil fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Tunjangan\"}');
INSERT INTO `p_setting_item` VALUES (694, 3, '', 0, 0, '{\"id_menu\":\"693\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (697, 3, '', 0, 0, '{\"id_menu\":\"695\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (698, 3, '', 0, 0, '{\"id_menu\":\"696\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (699, 2, 'Anggota', 676, 1, '{\"path_menu\":\"apppayroll/adm_wc/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Koperasi\"}');
INSERT INTO `p_setting_item` VALUES (700, 3, '', 0, 0, '{\"id_menu\":\"699\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (701, 2, 'Potongan', 676, 2, '{\"path_menu\":\"apppayroll/adm_wc/loan\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Potongan Koperasi\"}');
INSERT INTO `p_setting_item` VALUES (702, 3, '', 0, 0, '{\"id_menu\":\"701\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (705, 2, 'Olah F-KP', 704, 1, '{\"path_menu\":\"apppayroll/adm_fkp/edit\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data F-KP\"}');
INSERT INTO `p_setting_item` VALUES (704, 2, 'F-KP', 776, 7, '{\"path_menu\":\"apppayroll/adm_fkp/index\",\"icon_menu\":\"fa fa-sitemap fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi F-KP\"}');
INSERT INTO `p_setting_item` VALUES (706, 3, '', 0, 0, '{\"id_menu\":\"704\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (707, 3, '', 0, 0, '{\"id_menu\":\"705\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (708, 2, 'Dharma Wanita', 776, 10, '{\"path_menu\":\"apppayroll/adm_dw/index\",\"icon_menu\":\"fa fa-female fa-fw\",\"keterangan\":\"Pay Roll App - Administrasi Dharma Wanita\"}');
INSERT INTO `p_setting_item` VALUES (709, 3, '', 0, 0, '{\"id_menu\":\"708\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (711, 2, 'Potongan', 708, 2, '{\"path_menu\":\"apppayroll/adm_dw/loan\",\"icon_menu\":\"fa fa-edit fa-fw\",\"keterangan\":\"Pay Roll App - Olah Data Potongan Dharma Wanita\"}');
INSERT INTO `p_setting_item` VALUES (712, 3, '', 0, 0, '{\"id_menu\":\"710\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (713, 3, '', 0, 0, '{\"id_menu\":\"711\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (714, 2, 'Komponen Gaji', 641, 2, '{\"path_menu\":\"apppayroll/ref_component/index\",\"icon_menu\":\"fa fa-money\",\"keterangan\":\"Pay Roll App - Menu Referensi Komponen Gaji\"}');
INSERT INTO `p_setting_item` VALUES (715, 2, 'Gaji Pegawai Tetap', 714, 3, '{\"path_menu\":\"apppayroll/ref_component/permanent_employment\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Referensi Komponen Gaji Pegawai Tetap\"}');
INSERT INTO `p_setting_item` VALUES (716, 2, 'Gaji Pegawai Kontrak', 714, 4, '{\"path_menu\":\"apppayroll/ref_component/contract_employment\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Referensi Komponen Gaji Pegawai Kontrak\"}');
INSERT INTO `p_setting_item` VALUES (717, 2, 'Gaji Dewan Pengawas', 714, 5, '{\"path_menu\":\"apppayroll/ref_component/supervisory_boards\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Referensi Komponen Gaji Dewan Pengawas\"}');
INSERT INTO `p_setting_item` VALUES (718, 2, 'Gaji Direktur', 714, 6, '{\"path_menu\":\"apppayroll/ref_component/director_boards\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Referensi Komponen Gaji Direktur\"}');
INSERT INTO `p_setting_item` VALUES (719, 3, '', 0, 0, '{\"id_menu\":\"714\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (740, 2, 'Komponen Gaji Per Kelompok', 714, 2, '{\"path_menu\":\"apppayroll/ref_component/by_groups\",\"icon_menu\":\"fa fa-edit\",\"keterangan\":\"Pay Roll App - Menu Referensi Komponen Gaji Per Kelompok Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (724, 2, 'Zakat', 774, 11, '{\"path_menu\":\"apppayroll/adm_zakat/index\",\"icon_menu\":\"fa fa-share-alt\",\"keterangan\":\"Pay Roll App - Administrasi Zakat\"}');
INSERT INTO `p_setting_item` VALUES (725, 3, '', 0, 0, '{\"id_menu\":\"724\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (726, 2, 'Slip Gaji Pegawai', 656, 1, '{\"path_menu\":\"apppayroll/payslip/permanent\",\"icon_menu\":\"fa fa-money\",\"keterangan\":\"Pay Roll App - Slip Gaji Calon Pegawai dan Pegawai Tetap\"}');
INSERT INTO `p_setting_item` VALUES (727, 3, '', 0, 0, '{\"id_menu\":\"726\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (728, 2, 'Kelompok Penggajian', 641, 1, '{\"path_menu\":\"apppayroll/ref_payslip_groups/index\",\"icon_menu\":\"fa fa-building\",\"keterangan\":\"Pay Roll App - Referensi Kelompok Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (729, 2, 'Olah Data', 728, 1, '{\"path_menu\":\"apppayroll/ref_payslip_groups/edit\",\"icon_menu\":\"fa fa-pencil\",\"keterangan\":\"Pay Roll App - Olah Data Referensi Kelompok Penggajian\"}');
INSERT INTO `p_setting_item` VALUES (730, 3, '', 0, 0, '{\"id_menu\":\"728\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (731, 3, '', 0, 0, '{\"id_menu\":\"729\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (732, 2, 'Slip Gaji Pegawai Kontrak', 656, 2, '{\"path_menu\":\"apppayroll/payslip/contract\",\"icon_menu\":\"fa fa-money\",\"keterangan\":\"Pay Roll App - Slip Gaji Pegawai Kontrak\"}');
INSERT INTO `p_setting_item` VALUES (733, 2, 'Slip Gaji Direksi', 656, 3, '{\"path_menu\":\"apppayroll/payslip/directors\",\"icon_menu\":\"fa fa-money\",\"keterangan\":\"Pay Roll App - Slip Gaji Direksi\"}');
INSERT INTO `p_setting_item` VALUES (734, 2, 'Slip Gaji Dewan Pengawas', 656, 4, '{\"path_menu\":\"apppayroll/payslip/supervisory_boards\",\"icon_menu\":\"fa fa-money\",\"keterangan\":\"Pay Roll App - Slip Gaji Dewan Pengawas\"}');
INSERT INTO `p_setting_item` VALUES (735, 3, '', 0, 0, '{\"id_menu\":\"732\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (736, 3, '', 0, 0, '{\"id_menu\":\"733\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (737, 3, '', 0, 0, '{\"id_menu\":\"734\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (738, 2, 'Setup Komponen Gaji', 714, 1, '{\"path_menu\":\"apppayroll/ref_component/edit\",\"icon_menu\":\"fa fa-cog\",\"keterangan\":\"Pay Roll App - Menu Referensi Setup Komponen Gaji\"}');
INSERT INTO `p_setting_item` VALUES (739, 3, '', 0, 0, '{\"id_menu\":\"738\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (741, 3, '', 0, 0, '{\"id_menu\":\"740\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (742, 2, 'Tarif PTKP', 641, 6, '{\"path_menu\":\"apppayroll/ref_ptkp_tariff/index\",\"icon_menu\":\"fa fa-building\",\"keterangan\":\"Pay Roll App - Referensi Tarif PTKP\"}');
INSERT INTO `p_setting_item` VALUES (743, 2, 'Olah Data Tarif PTKP', 742, 1, '{\"path_menu\":\"apppayroll/ref_ptkp_tariff/edit\",\"icon_menu\":\"fa fa-pencil\",\"keterangan\":\"Pay Roll App - Referensi Olah Data Tarif PTKP\"}');
INSERT INTO `p_setting_item` VALUES (744, 3, '', 0, 0, '{\"id_menu\":\"742\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (745, 3, '', 0, 0, '{\"id_menu\":\"743\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (746, 2, 'Olah Data Zakat', 724, 1, '{\"path_menu\":\"apppayroll/adm_zakat/edit\",\"icon_menu\":\"fa fa-share-alt\",\"keterangan\":\"Pay Roll App - Olah data zakat\"}');
INSERT INTO `p_setting_item` VALUES (747, 3, '', 0, 0, '{\"id_menu\":\"746\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (748, 2, 'Shodaqoh', 774, 12, '{\"path_menu\":\"apppayroll/adm_shodaqoh/index\",\"icon_menu\":\"fa fa-share\",\"keterangan\":\"Pay Roll App - Administrasi Shodaqoh\"}');
INSERT INTO `p_setting_item` VALUES (749, 2, 'Olah Data Shodaqoh', 748, 1, '{\"path_menu\":\"apppayroll/adm_shodaqoh/edit\",\"icon_menu\":\"fa fa-share\",\"keterangan\":\"Pay Roll App - Olah Data Shodaqoh\"}');
INSERT INTO `p_setting_item` VALUES (750, 3, '', 0, 0, '{\"id_menu\":\"748\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (751, 3, '', 0, 0, '{\"id_menu\":\"749\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (752, 2, 'NPWP', 770, 4, '{\"path_menu\":\"apppayroll/adm_npwp/index\",\"icon_menu\":\"fa fa-cc\",\"keterangan\":\"Pay Roll App - Administrasi NPWP\"}');
INSERT INTO `p_setting_item` VALUES (753, 2, 'Olah Data NPWP', 752, 1, '{\"path_menu\":\"apppayroll/adm_npwp/edit\",\"icon_menu\":\"fa fa-cc\",\"keterangan\":\"Pay Roll App - Olah Data NPWP\"}');
INSERT INTO `p_setting_item` VALUES (754, 3, '', 0, 0, '{\"id_menu\":\"752\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (755, 3, '', 0, 0, '{\"id_menu\":\"753\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (756, 2, 'Tunjangan Khusus', 772, 9, '{\"path_menu\":\"apppayroll/adm_alw_advance/index\",\"icon_menu\":\"fa fa-beer\",\"keterangan\":\"Pay Roll App - Administrasi Tunjangan Khusus\"}');
INSERT INTO `p_setting_item` VALUES (757, 2, 'Olah Data Tunj. Khusus', 756, 1, '{\"path_menu\":\"apppayroll/adm_alw_advance/edit\",\"icon_menu\":\"fa fa-beer\",\"keterangan\":\"Pay Roll App - Olah Data Tunjangan Khusus\"}');
INSERT INTO `p_setting_item` VALUES (758, 3, '', 0, 0, '{\"id_menu\":\"756\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (759, 3, '', 0, 0, '{\"id_menu\":\"757\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (760, 2, 'TPTGR', 774, 13, '{\"path_menu\":\"apppayroll/adm_tptgr/index\",\"icon_menu\":\"fa fa-crop\",\"keterangan\":\"Pay Roll App -  Administrasi TPTGR\"}');
INSERT INTO `p_setting_item` VALUES (761, 2, 'Olah Data TPTGR', 760, 1, '{\"path_menu\":\"apppayroll/adm_tptgr/edit\",\"icon_menu\":\"fa fa-crop\",\"keterangan\":\"Pay Roll App - Olah Data TPTGR\"}');
INSERT INTO `p_setting_item` VALUES (762, 3, '', 0, 0, '{\"id_menu\":\"760\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (763, 3, '', 0, 0, '{\"id_menu\":\"761\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (764, 2, 'Rekening Air', 675, 7, '{\"path_menu\":\"apppayroll/adm_water_bill/index\",\"icon_menu\":\"fa fa-tint\",\"keterangan\":\"Pay Roll App - Administrasi Rekening Air\"}');
INSERT INTO `p_setting_item` VALUES (765, 2, 'Olah Data Rekening', 764, 1, '{\"path_menu\":\"apppayroll/adm_water_bill/edit\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Olah Data Rekening Air\"}');
INSERT INTO `p_setting_item` VALUES (766, 3, '', 0, 0, '{\"id_menu\":\"764\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (767, 3, '', 0, 0, '{\"id_menu\":\"765\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (768, 2, 'Olah Data Tagihan', 764, 2, '{\"path_menu\":\"apppayroll/adm_water_bill/billing\",\"icon_menu\":\"fa fa-tint\",\"keterangan\":\"Pay Roll App - Olah Data Tagihan Air\"}');
INSERT INTO `p_setting_item` VALUES (769, 3, '', 0, 0, '{\"id_menu\":\"768\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (770, 2, 'Kepegawaian', 675, 1, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-user\",\"keterangan\":\"Pay Roll App - Menu Administrasi Kepegawaian\"}');
INSERT INTO `p_setting_item` VALUES (771, 3, '', 0, 0, '{\"id_menu\":\"770\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (772, 2, 'Adm. Tunjangan', 675, 4, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-life-ring\",\"keterangan\":\"Pay Roll App - Menu Administrasi Tunjangan\"}');
INSERT INTO `p_setting_item` VALUES (773, 3, '', 0, 0, '{\"id_menu\":\"772\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (774, 2, 'Adm. Potongan', 675, 5, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-crop\",\"keterangan\":\"Pay Roll App - Menu Administrasi Potongan\"}');
INSERT INTO `p_setting_item` VALUES (775, 3, '', 0, 0, '{\"id_menu\":\"774\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (776, 2, 'Adm. Org. Pegawai', 675, 6, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-sitemap\",\"keterangan\":\"Pay Roll App - Menu Administrasi Organisasi Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (777, 3, '', 0, 0, '{\"id_menu\":\"776\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (778, 2, 'Olah Data Hari Kerja', 695, 2, '{\"path_menu\":\"apppayroll/adm_attn/working_day\",\"icon_menu\":\"fa fa-calendar\",\"keterangan\":\"Pay Roll App - Olah Data Hari Kerja\"}');
INSERT INTO `p_setting_item` VALUES (779, 3, '', 0, 0, '{\"id_menu\":\"778\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (780, 2, 'Tunjangan Lembur', 772, 10, '{\"path_menu\":\"apppayroll/adm_overtime/index\",\"icon_menu\":\"fa fa-tasks\",\"keterangan\":\"Pay Roll App - Administrasi Tunjangan Lembur\"}');
INSERT INTO `p_setting_item` VALUES (781, 2, 'Olah Data Lembur', 780, 1, '{\"path_menu\":\"apppayroll/adm_overtime/edit\",\"icon_menu\":\"fa fa-tasks\",\"keterangan\":\"Pay Roll App - Olah Data Lembur\"}');
INSERT INTO `p_setting_item` VALUES (782, 3, '', 0, 0, '{\"id_menu\":\"780\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (783, 3, '', 0, 0, '{\"id_menu\":\"781\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (784, 2, 'Data Tanggungan', 770, 3, '{\"path_menu\":\"apppayroll/adm_dependent/index\",\"icon_menu\":\"fa fa-child\",\"keterangan\":\"Pay Roll App - Administrasi Data Tanggungan\"}');
INSERT INTO `p_setting_item` VALUES (785, 2, 'Olah Data Tanggungan', 784, 1, '{\"path_menu\":\"apppayroll/adm_dependent/edit\",\"icon_menu\":\"fa fa-child\",\"keterangan\":\"Pay Roll App - Olah Data Tanggungan Pegawai\"}');
INSERT INTO `p_setting_item` VALUES (786, 3, '', 0, 0, '{\"id_menu\":\"784\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (787, 3, '', 0, 0, '{\"id_menu\":\"785\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (792, 2, 'Kelompok Tarif', 742, 2, '{\"path_menu\":\"apppayroll/ref_ptkp_tariff/group\",\"icon_menu\":\"fa fa-institution\",\"keterangan\":\"App Pay Roll - Kelompok Tarif PTKP\"}');
INSERT INTO `p_setting_item` VALUES (788, 2, 'Riwayat Status Nikah', 770, 2, '{\"path_menu\":\"apppayroll/adm_marstat/index\",\"icon_menu\":\"fa fa-heartbeat\",\"keterangan\":\"Pay Roll App - Administrasi Riwayat Status Pernikahan\"}');
INSERT INTO `p_setting_item` VALUES (789, 2, 'Olah Data Status Nikah', 788, 1, '{\"path_menu\":\"apppayroll/adm_marstat/edit\",\"icon_menu\":\"fa fa-heartbeat\",\"keterangan\":\"Pay Roll App - Olah Data Status Pernikahan\"}');
INSERT INTO `p_setting_item` VALUES (790, 3, '', 0, 0, '{\"id_menu\":\"788\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (791, 3, '', 0, 0, '{\"id_menu\":\"789\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (793, 3, '', 0, 0, '{\"id_menu\":\"792\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (794, 2, 'Gaji Pokok Direksi', 643, 2, '{\"path_menu\":\"apppayroll/ref_base_salary/directors\",\"icon_menu\":\"fa fa-university\",\"keterangan\":\"Pay Roll App - Olah Data Gaji Pokok Direksi\"}');
INSERT INTO `p_setting_item` VALUES (796, 2, 'Penghasilan Lain', 0, 35, '{\"path_menu\":\"#\",\"icon_menu\":\"fa fa-asterisk\",\"keterangan\":\"Pay Roll App - Menu Penghasilan Lain\"}');
INSERT INTO `p_setting_item` VALUES (797, 2, 'THR Idul Fitri', 796, 1, '{\"path_menu\":\"apppayroll/personnel expenses/thr_idul_fitri\",\"icon_menu\":\"fa fa-gift\",\"keterangan\":\"Pay Roll App - Olah Data THR Idul Fitri\"}');
INSERT INTO `p_setting_item` VALUES (798, 2, 'Insentif Ramadhan', 796, 2, '{\"path_menu\":\"apppayroll/personnel_expenses/incentive_ramadhan\",\"icon_menu\":\"fa fa-user-plus\",\"keterangan\":\"Pay Roll App - Olah Data Insentif Ramadhan\"}');
INSERT INTO `p_setting_item` VALUES (799, 2, 'Insentif Pendidikan', 796, 3, '{\"path_menu\":\"apppayroll/personnel_expenses/incentive_education\",\"icon_menu\":\"fa fa-graduation-cap\",\"keterangan\":\"Pay Roll App - Olah Data Insentif Pendidikan\"}');
INSERT INTO `p_setting_item` VALUES (800, 2, 'Insentif Akhir Tahun', 796, 4, '{\"path_menu\":\"apppayroll/personnel_expenses/incentive_end_year\",\"icon_menu\":\"fa fa-book\",\"keterangan\":\"Pay Roll App - Olah Data Insentif Akhir Tahun\"}');
INSERT INTO `p_setting_item` VALUES (801, 2, 'Jasa Produksi', 796, 5, '{\"path_menu\":\"apppayroll/personnel_expenses/production_performance\",\"icon_menu\":\"fa fa-industry\",\"keterangan\":\"Pay Roll App - Olah Data Jasa Produksi\"}');
INSERT INTO `p_setting_item` VALUES (827, 3, '', 0, 0, '{\"id_menu\":\"826\",\"group_id\":\"637\"}');
INSERT INTO `p_setting_item` VALUES (808, 2, 'DLL', 73, 4, '{\"path_menu\":\"cms\",\"icon_menu\":\"\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (809, 3, '', 0, 0, '{\"id_menu\":\"808\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (810, 2, 'Setting Item Dashboard', 808, 1, '{\"path_menu\":\"cmssetting/dashboard\",\"icon_menu\":\"\",\"keterangan\":\"-\"}');
INSERT INTO `p_setting_item` VALUES (811, 3, '', 0, 0, '{\"id_menu\":\"810\",\"group_id\":\"4\"}');
INSERT INTO `p_setting_item` VALUES (812, 111, '', 0, 0, '{\"text\":\"ABSENSI\",\"color\":\"rgb(12, 93, 197)\",\"module\":\"\",\"path\":\"admin/module/widget/absensi/dashboard\",\"note\":\"Data Absensi Pegawai\",\"icon\":\"fa-user\",\"status\":\"1\",\"idd\":\"644\"}');
INSERT INTO `p_setting_item` VALUES (813, 111, '', 0, 0, '{\"text\":\"Kenaikan Berkala\",\"color\":\"rgb(235, 146, 7)\",\"module\":\"widget/kenaikan_berkala/param:0,widget/kenaikan_berkala/param:1,widget/kenaikan_berkala/param:2\",\"path\":\"#\",\"note\":\"Kenaikan Berkala Pegawai\",\"icon\":\"fa-forward\",\"status\":\"1\",\"idd\":\"645\"}');
INSERT INTO `p_setting_item` VALUES (814, 111, '', 0, 0, '{\"text\":\"Kenaikan Peringkat\",\"color\":\"rgb(203, 102, 12)\",\"module\":\"widget/kenaikan_peringkat/param:0,widget/kenaikan_peringkat/param:1,widget/kenaikan_peringkat/param:2,\",\"path\":\"#\",\"note\":\"Kenaikan Peringkat Pegawai\",\"icon\":\"fa-search-plus\",\"status\":\"1\",\"idd\":\"646\"}');
INSERT INTO `p_setting_item` VALUES (815, 111, '', 0, 0, '{\"text\":\"Pensiun\",\"color\":\"rgb(135, 135, 134)\",\"module\":\"widget/pensiun/param:0,widget/pensiun/param:1,widget/pensiun/param:2,\",\"path\":\"#\",\"note\":\"\",\"icon\":\"fa-power-off\",\"status\":\"1\",\"idd\":\"647\"}');
INSERT INTO `p_setting_item` VALUES (816, 111, '', 0, 0, '{\"text\":\"Pegawai Kontrak\",\"color\":\"rgb(60, 241, 216)\",\"module\":\"widget/kontrak/param:0,widget/kontrak/param:1,widget/kontrak/param:2,\",\"path\":\"#\",\"note\":\"Pegawai Kontrak\",\"icon\":\"fa-user\",\"status\":\"1\",\"idd\":\"648\"}');
INSERT INTO `p_setting_item` VALUES (817, 111, '', 0, 0, '{\"text\":\"Calon Pegawai\",\"color\":\"rgb(23, 175, 47)\",\"module\":\"widget/capeg/param:0,widget/capeg/param:1,widget/capeg/param:3\",\"path\":\"#\",\"note\":\"\",\"icon\":\"fa-check\",\"status\":\"1\",\"idd\":\"649\"}');
INSERT INTO `p_setting_item` VALUES (818, 111, '', 0, 0, '{\"text\":\"Tunjangan Anak\",\"color\":\"rgb(201, 123, 66)\",\"module\":\"widget/tunjangan_anak\",\"path\":\"#\",\"note\":\"\",\"icon\":\"fa-tags\",\"status\":\"1\",\"idd\":\"650\"}');
INSERT INTO `p_setting_item` VALUES (819, 111, '', 0, 0, '{\"text\":\"Pegawai Cuti \",\"color\":\"rgb(19, 203, 108)\",\"module\":\"\",\"path\":\"admin/module/widget/cuti\",\"note\":\"\",\"icon\":\"fa-calendar\",\"status\":\"1\",\"idd\":\"651\"}');
INSERT INTO `p_setting_item` VALUES (820, 111, '', 0, 0, '{\"text\":\"Monografi Pegawai\",\"color\":\"rgb(21, 155, 17)\",\"module\":\"dashboard/monografi\",\"path\":\"admin/module/appbkpp/dashboard/monografi\",\"note\":\"\",\"icon\":\"fa-database\",\"status\":\"1\",\"idd\":\"652\"}');
INSERT INTO `p_setting_item` VALUES (821, 111, '', 0, 0, '{\"text\":\"Nominatif Pegawai\",\"color\":\"rgb(6, 60, 4)\",\"module\":\"\",\"path\":\"admin/module/widget/nominatif\",\"note\":\"\",\"icon\":\"fa-info\",\"status\":\"1\",\"idd\":\"653\"}');
INSERT INTO `p_setting_item` VALUES (822, 111, '', 0, 0, '{\"text\":\"Monitoring Pegawai SOTK\",\"color\":\"rgb(20, 8, 106)\",\"module\":\"widget/pegawai_sotk\",\"path\":\"admin/module/appbkpp/pegawai/aktif\",\"note\":\"\",\"icon\":\"fa-signal\",\"status\":\"1\",\"idd\":\"654\"}');
INSERT INTO `p_setting_item` VALUES (823, 111, '', 0, 0, '{\"text\":\"Penghargaan & Sanksi\",\"color\":\"rgb(14, 116, 11)\",\"module\":\"\",\"path\":\"admin/module/widget/sanksi\",\"note\":\"\",\"icon\":\"fa-star\",\"status\":\"1\",\"idd\":\"655\"}');
INSERT INTO `p_setting_item` VALUES (824, 2, 'Cuti Pegawai', 0, 32, '{\"path_menu\":\"module/widget/cuti\",\"icon_menu\":\"calendar-o\",\"keterangan\":\"cuti pegawai\"}');
INSERT INTO `p_setting_item` VALUES (825, 3, '', 0, 0, '{\"id_menu\":\"824\",\"group_id\":\"5\"}');
INSERT INTO `p_setting_item` VALUES (826, 2, 'Administrasi Sidik Jari', 695, 3, '{\"path_menu\":\"apppayroll/adm_attn_fp/edit\",\"icon_menu\":\"fa fa-id-badge\",\"keterangan\":\"Pay Roll App - Administrasi Sidik Jari\"}');
INSERT INTO `p_setting_item` VALUES (828, 4, 'admin_payroll', 0, 0, '{\"section_name\":\"admin_payroll\",\"back_office\":\"admin_payroll\",\"keterangan\":\"admin_payroll\"}');
INSERT INTO `p_setting_item` VALUES (829, 3, '', 0, 0, '{\"id_menu\":\"656\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (830, 3, '', 0, 0, '{\"id_menu\":\"726\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (831, 3, '', 0, 0, '{\"id_menu\":\"732\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (832, 3, '', 0, 0, '{\"id_menu\":\"733\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (833, 3, '', 0, 0, '{\"id_menu\":\"734\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (840, 3, '', 0, 0, '{\"id_menu\":\"647\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (841, 3, '', 0, 0, '{\"id_menu\":\"654\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (842, 3, '', 0, 0, '{\"id_menu\":\"675\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (843, 3, '', 0, 0, '{\"id_menu\":\"770\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (844, 3, '', 0, 0, '{\"id_menu\":\"788\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (845, 3, '', 0, 0, '{\"id_menu\":\"789\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (846, 3, '', 0, 0, '{\"id_menu\":\"784\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (847, 3, '', 0, 0, '{\"id_menu\":\"785\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (848, 3, '', 0, 0, '{\"id_menu\":\"752\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (849, 3, '', 0, 0, '{\"id_menu\":\"753\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (850, 3, '', 0, 0, '{\"id_menu\":\"643\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (851, 3, '', 0, 0, '{\"id_menu\":\"649\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (853, 3, '', 0, 0, '{\"id_menu\":\"695\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (854, 3, '', 0, 0, '{\"id_menu\":\"696\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (855, 3, '', 0, 0, '{\"id_menu\":\"778\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (856, 3, '', 0, 0, '{\"id_menu\":\"826\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (857, 3, '', 0, 0, '{\"id_menu\":\"772\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (858, 3, '', 0, 0, '{\"id_menu\":\"683\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (859, 3, '', 0, 0, '{\"id_menu\":\"685\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (860, 3, '', 0, 0, '{\"id_menu\":\"756\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (861, 3, '', 0, 0, '{\"id_menu\":\"757\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (862, 3, '', 0, 0, '{\"id_menu\":\"780\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (863, 3, '', 0, 0, '{\"id_menu\":\"781\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (864, 3, '', 0, 0, '{\"id_menu\":\"774\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (865, 3, '', 0, 0, '{\"id_menu\":\"724\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (866, 3, '', 0, 0, '{\"id_menu\":\"746\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (867, 3, '', 0, 0, '{\"id_menu\":\"748\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (868, 3, '', 0, 0, '{\"id_menu\":\"749\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (869, 3, '', 0, 0, '{\"id_menu\":\"760\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (870, 3, '', 0, 0, '{\"id_menu\":\"761\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (871, 3, '', 0, 0, '{\"id_menu\":\"776\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (872, 3, '', 0, 0, '{\"id_menu\":\"676\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (873, 3, '', 0, 0, '{\"id_menu\":\"699\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (874, 3, '', 0, 0, '{\"id_menu\":\"701\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (875, 3, '', 0, 0, '{\"id_menu\":\"704\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (876, 3, '', 0, 0, '{\"id_menu\":\"705\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (877, 3, '', 0, 0, '{\"id_menu\":\"708\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (878, 3, '', 0, 0, '{\"id_menu\":\"710\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (879, 3, '', 0, 0, '{\"id_menu\":\"711\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (880, 3, '', 0, 0, '{\"id_menu\":\"764\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (881, 3, '', 0, 0, '{\"id_menu\":\"765\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (882, 3, '', 0, 0, '{\"id_menu\":\"768\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (883, 3, '', 0, 0, '{\"id_menu\":\"679\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (884, 3, '', 0, 0, '{\"id_menu\":\"681\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (885, 3, '', 0, 0, '{\"id_menu\":\"658\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (886, 3, '', 0, 0, '{\"id_menu\":\"669\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (887, 3, '', 0, 0, '{\"id_menu\":\"641\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (888, 3, '', 0, 0, '{\"id_menu\":\"728\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (889, 3, '', 0, 0, '{\"id_menu\":\"729\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (890, 3, '', 0, 0, '{\"id_menu\":\"714\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (891, 3, '', 0, 0, '{\"id_menu\":\"738\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (892, 3, '', 0, 0, '{\"id_menu\":\"740\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (897, 3, '', 0, 0, '{\"id_menu\":\"661\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (898, 3, '', 0, 0, '{\"id_menu\":\"667\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (899, 3, '', 0, 0, '{\"id_menu\":\"693\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (900, 3, '', 0, 0, '{\"id_menu\":\"687\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (901, 3, '', 0, 0, '{\"id_menu\":\"688\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (902, 3, '', 0, 0, '{\"id_menu\":\"691\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (903, 3, '', 0, 0, '{\"id_menu\":\"742\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (904, 3, '', 0, 0, '{\"id_menu\":\"743\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (905, 3, '', 0, 0, '{\"id_menu\":\"792\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (910, 2, 'Dashboard', 0, 33, '{\"path_menu\":\"apppayroll/dashboard/index\",\"icon_menu\":\"fa fa-desktop fa-fw\",\"keterangan\":\"Pay Roll App - Dashboard\"}');
INSERT INTO `p_setting_item` VALUES (912, 3, '', 0, 0, '{\"id_menu\":\"910\",\"group_id\":\"828\"}');
INSERT INTO `p_setting_item` VALUES (973, 2, 'Laporan Payslip', 658, 2, '{\"path_menu\":\"apppayroll/report/payslip\",\"icon_menu\":\"fa fa-bar-chart\",\"keterangan\":\"Menu Laporan Payslip\"}');
INSERT INTO `p_setting_item` VALUES (974, 3, '', 0, 0, '{\"id_menu\":\"973\",\"group_id\":\"828\"}');

SET FOREIGN_KEY_CHECKS = 1;
